services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - 8081:80
    depends_on:
      - reverse-proxy
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8090:8090
    depends_on:
      - reverse-proxy
  reverse-proxy:
    build: 
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 8443:8443
